# Overhorsed Version 1.0 DEV
enchanting:
  # Controls what enchantments are permitted on horse armor.
  # Controls whether enchantments can be obtained from enchantment table (if not treasure)
  # and if they can be applied/combined via anvil.
  horse_armor_enchantment_pool:
    - minecraft:frost_walker
    - minecraft:protection
    - minecraft:projectile_protection
    - minecraft:blast_protection
    - minecraft:feather_falling
    - minecraft:frost_walker
    - minecraft:soul_speed
    - minecraft:thorns
    - overhorsed:strafing
    - overhorsed:leaping

  enchantments:
    # Enchantment that increases side-to-side speed of mounted horse.
    strafing:
      enabled: true
      max_level: 3
      treasure: false
      factor: 0.25 # Percentage of speed added per level

    # Enchantment that increases jump height of mounted horse.
    leaping:
      enabled: true
      max_level: 2
      treasure: false
      factor: 0.5 # Percentage of jump height added per level

# Client settings
client:
  smithing_table:
    # Controls how fast the horse model spins in the smithing table
    rotation_increment: -0.025
    # Multiplies above value by this while hovering over the model
    hover_rotation_modifier: 0.5
    # Where the horse is placed on the screen. Might want to leave this one alone.
    horse_offset_x: 151
    horse_offset_y: 61
    # Size of the horse. I'd leave this one alone, probably.
    horse_scale: 25
    # Size of horse when hovering over it.
    hover_scale: 35
    # How many frames it takes to grow to the size above.
    frame_time: 7